### ISSUE TITLE
Generalizability of the model

### ISSUE THREAD

**Issue by ParamXw** [songbowang125/SVision-pro#12]
My research is in the direction of a plant and I would like to ask if your model can be migrated to a plant

**Comment by songbowang125** [comment]
Hi, 

Thanks for using SVision-pro. Of course the models can be migrated to plants, as long as the input follows the BAM format.

**Comment by ParamXw** [comment]
I would like to ask, which mode should I use if I am detecting csv of plants?

**Comment by songbowang125** [comment]
The 256/512/1024 models correspond to three differenct image size settings (256x256, 512x512 and 1024x1024), which determine the minimum detectable SV frequencies (0.04, 0.02 and 0.01, respectively). If you are detecting germline and denovo CSVs, 256 model is enough.

**Comment by ParamXw** [comment]
thanks!So how do I choose between 'germline', 'somatic', 'denovo', 'genotype'?

**Comment by songbowang125** [comment]
If you detect CSV from independent samples, it is germline. Denovo and somatic are used for family datasets (parents and children) and tumor datasets (normal-tumor paired samples), respectively. Genotype only detects the given genome region. 

For plants, I assume you need to detect germline CSVs.

**Comment by ParamXw** [comment]
Thanks a million for your answer!
