### ISSUE TITLE
model prediction

### ISSUE THREAD

**Issue by ParamXw** [songbowang125/SVision-pro#13]
/
![QQ20241031-163706](https://github.com/user-attachments/assets/f2acfba7-d357-43d6-b111-6b202b332433)
I run the genome of a plant through the second step and it just ends.

**Comment by songbowang125** [comment]
Would you mind to send me your commands? And was there any output?

**Comment by ParamXw** [comment]
command:SVision-pro --target_path /home/jktest/XW/support/Saf_YH_AH.sort.bam  --genome_path /home/jktest/XW/ref/Saf_YH_genome_chr12.fa --model_path ./src/pre_process/model_liteunet_256_8_16_32_32_32.path  --sample test-Saf --out_path /home/jktest/XW/output  --detect_mode germline --process 8
![QQ20241031-164552](https://github.com/user-attachments/assets/86adcbfd-ac20-4fd0-bf33-184cb543fb38)
It can output, but the number is too small compared to the sv I found with cuteSV

**Comment by songbowang125** [comment]
You are calling germline SVs, so the model (for genotyping among samples) doesn't need to work. Was there any error in your running log file (file ending with .log)

**Comment by ParamXw** [comment]
The log file is not reporting errors.

**Comment by ParamXw** [comment]
Too few sv's detected, is there any way to do this, do I need to fine tune the model?

**Comment by songbowang125** [comment]
I think it's not about the models but something about the naming differences between human and plant chromosomes. I see these SVs are called from partial regions of only four chromosomes. Did the log files report the calling process from other chromosomes? The log file will record information like ' Collecting chromxxx, xxx candidate events found'. I would need your log file to find the reason.

**Comment by ParamXw** [comment]
[test-Saf.svision_pro_v2.0.s5.log](https://github.com/user-attachments/files/17585462/test-Saf.svision_pro_v2.0.s5.log)
All the chromosomes are called, here's my log file

**Comment by songbowang125** [comment]
Thanks for that, I think the reads in your BAM file are somehow filtered out due to the quality control processes. Was your read sequenced in HiFi or ONT plantform?

**Comment by ParamXw** [comment]
hifi

**Comment by songbowang125** [comment]
Ok, then you may add the parameter '--skip_mismatch_filter' to your command line and check if the outputs are refined compared with the previous run.

**Comment by ParamXw** [comment]
The results are a very noticeable improvement, thanks. One more question, you mentioned that I chose genotype and didn't call the model, which I kind of didn't understand. I predicted sv this way and didn't use a deep learning model?
