### ISSUE TITLE
指标分析

### ISSUE THREAD

**Issue by Bigdata20688** [songbowang125/SVision-pro#16]
作者您好，我目前已按照操作步骤跑出结果/root/SVision-pro/test_out/test.svision_pro_v2.1.s5.vcf文件，目前想通过truvari工具进行与基准vcf文件进行准确率和召回率的指标分析，不知道您的基准文件是哪一个或者有无基准文件的下载链接地址呢？
期待您的回复，谢谢

**Comment by Bigdata20688** [comment]
您好，我是用truvari工具将跑出来的文件test.svision_pro_v2.1.s5.vcf和HG002_SVs_Tier1_v0.6.vcf基准文件进行对比想进行指标分析，但运行结果中只含有FP这个指标，TP、召回率等指标结果为0或null为什么呢
[运行结果.txt](https://github.com/user-attachments/files/17710847/default.txt)

**Comment by songbowang125** [comment]
请检查使用的参考基因组版本，HG002_SVs_Tier1_v0.6.vcf使用的为GRCh37参考基因组。

另外，一般HG002比较会使用high confident区间([HG002_SVs_Tier1_v0.6.bed](https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/NIST_SV_v0.6/HG002_SVs_Tier1_v0.6.bed)。

完整truvari命令为‘truvari bench -b {} -c {} --includebed {} -r 1000 -p 0 -f {} -o {} --passonly’

**Comment by Bigdata20688** [comment]
感谢您提供的帮助，我按照您的建议进行操作，其中‘truvari bench -b {} -c {} --includebed {} -r 1000 -p 0 -f {} -o {} --passonly’该命令中的-f后的参数我没输入，您有可供参考的过滤文件作为输入参数吗？但是在未输入该参数情况下也跑出结果了，结果保存在如下文档中
[运行结果.txt](https://github.com/user-attachments/files/17713655/default.txt)
十分感谢您

**Comment by Bigdata20688** [comment]
感谢您的回复，想请问下您truvari bench -b {} -c {} --includebed {} -r 1000 -p 0 -f {} -o {} --passonly该命令中的-f后的所需要的过滤文件是什么呢？

**Comment by Bigdata20688** [comment]
您好，根据您的建议我输入如下命令“truvari bench -b /root/SVision-pro/test_out/HG002_SVs_Tier1_v0.6.vcf.gz -c /root/SVision-pro/test_out/test.svision_pro_v2.1.s5.vcf.gz --includebed /root/SVision-pro/test_out/HG002_SVs_Tier1_v0.6.bed -r 1000 -p 0  -o /output_dir --passonly”其中未使用您提供的参考命令中的-f参数，运行结果保存在如下文档中，结果中只含有fn指标，您有可供参考的建议吗？
[Uploading 运行结果.txt…]()

期待您的回复，谢谢！

**Comment by songbowang125** [comment]
-f 是指定参考基因组的参数。从第一次发给我的“运行结果.txt”来看，参考基因组版本不一致，因此需要检查参考基因组，HG002 Tier1 0.6使用的是GRCh37。

第二次发送的“运行结果.txt”无法打开

**Comment by Bigdata20688** [comment]
谢谢您的回复，我昨天重新运行了svision pro采用的GRCh37参考基因组运行出“test.svision_pro_v2.1.s5.vcf”该文件；
您说的意思是-f后面填写的值应为GRch37吗；
再次运行的结果如下文档：
[运行结果.txt](https://github.com/user-attachments/files/17725261/default.txt)

**Comment by Bigdata20688** [comment]
谢谢您的回复，我昨天重新运行了svision pro，采用的GRCh37参考基因组，运行出“test.svision_pro_v2.1.s5.vcf”该文件；
您说的意思是-f后面填写的值应为GRch37.fa吗；
再次运行的结果如下文档：
[运行结果.txt](https://github.com/user-attachments/files/17725261/default.txt)

**Comment by songbowang125** [comment]
你的BAM文件是比对到GRCh37的吗？只更换SVision-pro的不起作用，输入文件不是GRCh37比对的

**Comment by Bigdata20688** [comment]
感谢您的回复，目前我的对比指标思路是：
通过您开源的svision-pro项目中，按照输入的参考基因组是GRCH38.fa,并运行出结果：test.svision_pro_v2.1.s5.vcf，我目前采用的基准文件HG002_SVs_Tier1_v0.6.vcf应该是基于Grch37.fa，所以问题应该是基准文件未使用正确
目前的想法是：使用以GRch38.fa为参考基因组跑出来的test.svision_pro_v2.1.s5.vcf与基准文件进行对比，请问正确的基准文件应该是哪一个呢？以及我仍然想采用truvari工具，是否仍要填写其中的--includebed和-f参数呢？
期待您的回复。

**Comment by songbowang125** [comment]
目前没有GRCh38版本的基准文件，HG002数据请使用GRCh37重新进行比对。

或者，有一种不精确的做法，使用liftover将37版本的基准文件（包括VCF和BED）转换为38版本

**Comment by Bigdata20688** [comment]
作者您好，想了解一下您的该项目当时是如何通过指标分析的呢？因为我认为不是应该通过最终跑出来的test.svision_pro_v2.1.s5.vcf文件进行对比吗？但该文件是基于grch38版本的，所以想了解您当时的指标分析方法可以吗？谢谢。

**Comment by songbowang125** [comment]
我是将HG002原始数据比对到了GRCh37，然后进行变异检测和评估，这一点在我的文章里说明了，并且这也是领域内的标准做法

**Comment by Bigdata20688** [comment]
好的谢谢，因为最初根据您github中提供的运行步骤要先下载grch38参考基因，所以跑出的结果应该是基于grch38的，按照您的建议”你的BAM文件是比对到GRCh37的吗？只更换SVision-pro的不起作用，输入文件不是GRCh37比对的“意思是我要重新更换相应的bam文件以grch37为参考基因组，运行该项目，然后再使用truvari工具将结果与HG002_SVs_Tier1_v0.6.vcf进行指标分析，是这个意思吗？或者您有无其他更好的建议呢？

**Comment by songbowang125** [comment]
github中提供的只是实例运行，不代表其他样本运行。

输入，检测，评估，这三部分的参考基因组必须保持一致，否则没有意义。

**Comment by Bigdata20688** [comment]
感谢您的回复，由于目前的工作是在初步阶段，所以以为指标分析就是通过truvari将该项目的结果文件与基准文件进行对比，然后看到您的svision-pro-utils项目中有相应的truvari对比，是否有可供参考的对比方式呢？个人准备进一步深入研读您的论文寻找可供参考的方法，十分感谢，耽误您的宝贵时间了。

**Comment by Bigdata20688** [comment]
作者您好，耽误您宝贵的时间了，通过思考我整理了一下自己的想法想与您交流一下，我理解的整个的结构变异检测的流程以及各个文件的作用：
比如来了一个人我要去检测他的基因序列哪里变异了，首先我要先测出来他的基因序列，也就是fastq文件格式，然后与人类参考基因组进行比对，也就是与GrCH37/38（该参考基因序列是包含人类正常变异序列的）文件进行比对，比对的目的是检索我测出的序列在该参考基因组序列的哪个位置（对齐，可能还含有其他信息），这个比对结果也就是bam文件，是二进制的机器可识别的，然后再将该文件用SVision-pro进行识别最终生成包含变异信息的vcf文件。
如果我要进行指标分析，意味着我的bam文件需要用fastaq文件与grch37文件重新对比生成，然后重新识别变异信息生成新的vcf文件，不知道我的理解对不对，望您指正。

**Comment by Bigdata20688** [comment]
或者请问您是否有HG002基于37版本的bam文件呢？

**Comment by Bigdata20688** [comment]
滴滴~

**Comment by songbowang125** [comment]
> 呢？

我是下载fastq文件自己比对的

**Comment by Bigdata20688** [comment]
好的，放便问一下您文章中所给的HG002指标分析的召回率、准确率以及F1可视化图，所以开始使用的测序数据具体是哪一个呢？因为后续可能要以您的指标作为参考进行分析，麻烦您了

**Comment by songbowang125** [comment]
详细数据和链接放在了文章Data availability章节。

**Comment by Bigdata20688** [comment]
好的谢谢啦



---原始邮件---
发件人: "Songbo ***@***.***&gt;
发送时间: 2024年11月22日(周五) 中午11:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [songbowang125/SVision-pro] 指标分析 (Issue #16)




 
详细数据和链接放在了文章Data availability章节。
