### ISSUE TITLE
About the model liteunet ,which should I use?

### ISSUE THREAD

**Issue by Davidseye** [songbowang125/SVision-pro#2]
I notice that there are 3 different model, 256/521/1024, what is the difference between them, what should I use to detect somatic sv?

**Comment by songbowang125** [comment]
The 256/521/1024 models correspond to three differenct image size settings (256x256, 512x512 and 1024x1024), which determine the minimum detectable SV frequencies (0.04, 0.02 and 0.01). The description about this setting could be found in the Method section of our paper (https://doi.org/10.1038/s41587-024-02190-7)

In common, image size 256 (defaulted) is capable for most conditions. So, you can use the 256 model. While if you use other models/image sizes, please use this two parameters simultaneously: 

SVision-pro ... ... --img_size 512 --model_path liteunet.512.model.pth, or 
SVision-pro ... ... --img_size 1024--model_path liteunet.1024.model.pth

**Comment by Davidseye** [comment]
hi！ I've been used Svision-pro to detect somatic sv through HCC1395/bl (the benchmarker in the paper) . I used the code be like :
 SVision-pro --target_path /tumor.ont.bam  --base_path /normal.ont.bam --genome_path /hg38.fa  --model_path /SVision-pro/src/pre_process/model_liteunet_1024_8_16_32_32_32.pth --out_path /outfile --sample_name somatic.stan --detect_mode somatic  
,but I cant get the true positive rate I wanted. I get 19563 sv .  Could u tell me what is the problem with my code?

**Comment by songbowang125** [comment]
Here is the cmd I used for the HCC1395 ONT data : 

SVision-pro --target_path xxx.bam --base_path xxx.bam --model_path model_liteunet_1024_8_16_32_32_32.pth --access_path hg38.access.10M.bed --out_path  --genome_path GRCh38.fasta --sample_name test --min_supp 2 --preset error-prone --process_num 48 --detect_mode somatic --img_size 1024 --skip_nearby --rescue_large

I believe that the minimun supporting read number (--min_supp) is a key parameter for true positive rate.
