### ISSUE TITLE
About the FILTER line in VCF file

### ISSUE THREAD

**Issue by WenliangGuo** [songbowang125/SVision-pro#3]
Hi Team,
Thank you so much for developing this great tool
I do have one quick question to be asked that:
```
##FILTER=<ID=POLY,Description="Polymorphic">
```
What does this Polymorphic mean in this row?
Thanks

**Comment by songbowang125** [comment]
Thanks for using SVision-pro. 

'Polymorphic' means there are more than one SVs within a small genome region (e.g. 200bp or 1000bp).  It is just a marker for this condition.
