### ISSUE TITLE
The output vcf file is empty.

### ISSUE THREAD

**Issue by ShangariR** [songbowang125/SVision-pro#4]
Hello, thank you for developing the tool. I am new to WGS analysis and subsequently the tool .I am trying to run it for somatic tumor/control samples. I have installed the tool successfully according to the dependencies. 
While running the tool the output is given within seconds and it produces a empty file (VCF file is empty)

This is the command i used:

SVision-pro --target_path xxx.bam --base_path yyy.bam --model_path model_liteunet_1024_8_16_32_32_32.pth --out_path /path/ --genome_path hg38.fa --sample_name test --min_supp 2 --preset error-prone --process_num 48 --detect_mode somatic --img_size 1024 --skip_nearby --rescue_large

Log File:
![Log file](https://github.com/songbowang125/SVision-pro/assets/84325003/bede098c-c5d3-4b05-824d-299df898ef35)
Output VCF file
![vcf file](https://github.com/songbowang125/SVision-pro/assets/84325003/b6b76766-216c-47d6-93bd-2f65d6528a63)

Any help would be appreciated. Thanks

**Comment by songbowang125** [comment]
It appears that the Step1 scans no interval in your sample. Was your BAM file aligned to the same reference specified in the command line?

**Comment by ShangariR** [comment]
I used the pacbio dataset and GRCh38 reference genome mentioned in the article

**Comment by songbowang125** [comment]
In your image showing the 'Output VCF file', you used NCC2-T.bam as the tumor BAM file and NCC2-BL.bam as the normal BAM file.  Which article does this data come from? I will run them myself for debugging and then send you the reasons.

**Comment by ShangariR** [comment]
Hi, am sorry for the confusion, please ignore that image. This is the output VCF file after using the pacbio dataset
![vcf file (2)](https://github.com/songbowang125/SVision-pro/assets/84325003/10f2ac88-036e-431f-a438-1913d1103eb8)
The tumor BAM file is m84039_230414_235240_s2.hifi_reads.default.bam and normal BAM file is m84039_230412_183900_s2.hifi_reads.bc2002.bam

**Comment by songbowang125** [comment]
While, in my practice, BAM files, names like m'84039_230414_235240_s2.hifi_reads', are not real alignment BAM files but for storing the raw CCS subreads. You can use Samtools to check that. Therefore, you need to map those subreads to reference genome using pbmm2 or convert those subreads to Fastq files and align them using minimap2

**Comment by ShangariR** [comment]
Sure will check that. Thank you
