### ISSUE TITLE
No BND/TRA event in the SVision-pro output

### ISSUE THREAD

**Issue by ywzhang071394** [songbowang125/SVision-pro#8]
Hi,

Thank you for publishing this nice tool, which does help a lot in our study. However, I was confused by the output vcf file. 
I saw that the SVTYPE tags include INS, DEL, DUP, tDUP (tandem duplication) and INV but lack BND/TRA. 
It will be tricky when combining SVision-pro VCF with other callers.
Could you help to check why this happened?

Thanks

**Comment by ywzhang071394** [comment]
My understanding is that a TRA event with breadends A-B in SVision-pro was represented by a DEL event on the breadend ‘A’ and an INS event on the breadend ‘B’. Is this true?

**Comment by songbowang125** [comment]
Actually, current version of SVision-pro does not output BNDs or TRAs. The 'A-B' example you mentioned might be a complex 'DEL+INS', which is also called as a replacement. We will consider adding the BND/TRA in the next version

**Comment by ywzhang071394** [comment]
Thank you for the reply.
Is SVision-pro able to detect SVs at the so-called BND/TRA sites and just call them using other names?
In other word, is the absence of BNDs due to the naming rule or just the incapacity of detecting such kind of SVs?

**Comment by songbowang125** [comment]
Currently, we just filter out all BND/TRA like sites by detemining whether they are inter-chromosome events or intra-chromosome events with size larger than 50kb.

**Comment by ywzhang071394** [comment]
Thank you! I am gonna closing this issue!

**Comment by songbowang125** [comment]
Hi, I have upgraded SVision-pro into the v2.0 version, and now it can call BND events. You can try the new version for BND calling and I am very happy to receive any feedbacks.

**Comment by ywzhang071394** [comment]
Thank you for letting me know! Will try and get back to you soon.
