### ISSUE TITLE
Germline variant call

### ISSUE THREAD

**Issue by jjuhyunkim** [songbowang125/SVision-pro#9]
Hi! 

Can I use the file `${prefix}.svision_pro_v1.8.s5.vcf.gz` for downstream analysis of both somatic and germline variants?
I've used `--detect_mode somatic`

Thanks!

**Comment by songbowang125** [comment]
Of course you can use the VCF from '--detect_mode somatic' for both somatic and germline analysis since the VCF contains all SVs in your 'target file'.

**Comment by jjuhyunkim** [comment]
Thank you for clarifying! :)
